/**
 * Shared types for backend and frontend
 * 
 * This file contains DTOs (Data Transfer Objects) and Command Models
 * that represent data structures used by the API endpoints.
 * All types are derived from database models to ensure type safety.
 */

import type { Tables, TablesInsert, TablesUpdate } from './db/database.types';

// ============================================================================
// ENTITY TYPES (Database Models)
// ============================================================================

/**
 * Flashcard entity from database
 */
export type FlashcardEntity = Tables<'flashcards'>;

/**
 * Generation entity from database
 */
export type GenerationEntity = Tables<'generations'>;

/**
 * Generation error log entity from database
 */
export type GenerationErrorLogEntity = Tables<'generation_error_logs'>;

// ============================================================================
// LITERAL TYPES
// ============================================================================

/**
 * Valid flashcard source values
 * - 'ai-full': Generated by AI and accepted without modifications
 * - 'ai-edited': Generated by AI but edited before accepting
 * - 'manual': Created manually by user
 */
export type FlashcardSource = 'ai-full' | 'ai-edited' | 'manual';

// ============================================================================
// FLASHCARD DTOs
// ============================================================================

/**
 * Flashcard DTO returned by API endpoints
 * Excludes user_id for security (will be inferred from auth context)
 */
export type FlashcardDTO = Omit<FlashcardEntity, 'user_id'>;

/**
 * Single flashcard creation command
 * Used when creating a single flashcard (manual or from generation)
 */
export type FlashcardCreateCommand = {
  front: string;
  back: string;
  source: FlashcardSource;
  generation_id?: number | null;
};

/**
 * Batch flashcard creation command
 * Used when accepting multiple flashcards from AI generation
 */
export type FlashcardBatchCreateCommand = {
  flashcards: FlashcardCreateCommand[];
};

/**
 * Flashcard update command
 * Only front and back can be updated
 * Source will be automatically changed to 'ai-edited' if original was 'ai-full'
 */
export type FlashcardUpdateCommand = {
  front?: string;
  back?: string;
};

/**
 * Query parameters for listing flashcards
 */
export type FlashcardListQuery = {
  page?: number;
  limit?: number;
  source?: FlashcardSource;
  search?: string;
};

/**
 * Response for flashcard list endpoint
 */
export type FlashcardListResponse = PaginatedResponse<FlashcardDTO>;

// ============================================================================
// GENERATION DTOs
// ============================================================================

/**
 * Generation DTO returned by API endpoints
 * Excludes user_id for security (will be inferred from auth context)
 */
export type GenerationDTO = Omit<GenerationEntity, 'user_id'>;

/**
 * Proposed flashcard returned by AI generation
 * Does not have id, timestamps, or metadata yet
 */
export type ProposedFlashcard = {
  front: string;
  back: string;
  source: "ai-full";
};

/**
 * Generation creation command
 * Used when requesting AI to generate flashcards from source text
 */
export type GenerationCreateCommand = {
  source_text: string;
};

/**
 * Response after creating a generation
 * Includes generation metadata and proposed flashcards (not yet saved)
 */
export type GenerationCreateResponse = {
  generation: GenerationDTO;
  proposed_flashcards: ProposedFlashcard[];
};

/**
 * Generation details with associated flashcards
 * Used by GET /api/generations/{id} endpoint
 */
export type GenerationDetailDTO = GenerationDTO & {
  flashcards: Pick<FlashcardDTO, 'id' | 'front' | 'back' | 'source'>[];
};

/**
 * Query parameters for listing generations
 */
export type GenerationListQuery = {
  page?: number;
  limit?: number;
};

/**
 * Response for generation list endpoint
 */
export type GenerationListResponse = PaginatedResponse<GenerationDTO>;

// ============================================================================
// PAGINATION
// ============================================================================

/**
 * Pagination metadata
 */
export type PaginationMeta = {
  page: number;
  limit: number;
  total: number;
  total_pages: number;
};

/**
 * Generic paginated response
 */
export type PaginatedResponse<T> = {
  data: T[];
  pagination: PaginationMeta;
};

// ============================================================================
// ERROR HANDLING
// ============================================================================

/**
 * Error codes used across the API
 */
export type ApiErrorCode =
  | 'VALIDATION_ERROR'
  | 'NOT_FOUND'
  | 'CONFLICT'
  | 'UNAUTHORIZED'
  | 'FORBIDDEN'
  | 'RATE_LIMIT_EXCEEDED'
  | 'INTERNAL_SERVER_ERROR'
  | 'SERVICE_UNAVAILABLE'
  | 'UNPROCESSABLE_ENTITY';

/**
 * Error detail object with additional context
 */
export type ApiErrorDetail = {
  field?: string;
  constraint?: string;
  [key: string]: unknown;
};

/**
 * Standardized API error response
 */
export type ApiError = {
  error: {
    code: ApiErrorCode;
    message: string;
    details?: ApiErrorDetail;
  };
};

// ============================================================================
// DATABASE INSERT/UPDATE TYPES (for internal use)
// ============================================================================

/**
 * Internal type for inserting flashcard into database
 * Includes user_id which is added server-side from auth context
 */
export type FlashcardInsert = TablesInsert<'flashcards'>;

/**
 * Internal type for updating flashcard in database
 */
export type FlashcardUpdate = TablesUpdate<'flashcards'>;

/**
 * Internal type for inserting generation into database
 * Includes user_id which is added server-side from auth context
 */
export type GenerationInsert = TablesInsert<'generations'>;

/**
 * Internal type for updating generation in database
 */
export type GenerationUpdate = TablesUpdate<'generations'>;

/**
 * Internal type for logging generation errors
 */
export type GenerationErrorLogInsert = TablesInsert<'generation_error_logs'>;

// ============================================================================
// FLASHCARDS VIEW MODELS (Frontend specific types)
// ============================================================================

/**
 * Stan dialogu w FlashcardsView
 * Określa, który dialog jest otwarty i z jakimi danymi
 */
export type DialogState = 
  | { type: 'closed' }
  | { type: 'create' }
  | { type: 'edit'; flashcard: FlashcardDTO }
  | { type: 'delete'; flashcard: FlashcardDTO };

/**
 * Dane formularza fiszki
 * Używane przez FlashcardForm do walidacji i submitu
 */
export type FlashcardFormData = {
  front: string;
  back: string;
};

/**
 * Rozszerzony filtr źródła z opcją "all"
 * Używany w FlashcardToolbar
 */
export type SourceFilterValue = FlashcardSource | 'all';

/**
 * Props dla komponentów toast notifications
 */
export type ToastMessage = {
  type: 'success' | 'error' | 'info';
  title: string;
  description?: string;
};

/**
 * Stan ładowania dla różnych operacji
 */
export type LoadingState = {
  isLoading: boolean; // ładowanie listy
  isSaving: boolean;  // zapisywanie create/edit
  isDeleting: boolean; // usuwanie fiszki
};

/**
 * Stan błędu
 */
export type ErrorState = {
  message: string;
  code?: ApiErrorCode;
} | null;

// ============================================================================
// DASHBOARD VIEW MODELS (Frontend specific types)
// ============================================================================

/**
 * Agregowane statystyki dla dashboardu użytkownika
 */
export type DashboardStats = {
  /** Całkowita liczba fiszek użytkownika */
  totalFlashcards: number;
  
  /** Liczba wykonanych generacji AI */
  totalGenerations: number;
  
  /** Wskaźnik akceptacji fiszek AI w procentach (0-100) */
  acceptanceRate: number;
  
  /** Liczba fiszek oczekujących na naukę (dla MVP może być 0) */
  flashcardsDueForStudy: number;
};

/**
 * Propsy dla komponentu StatsCard
 */
export type StatsCardProps = {
  icon: React.ReactNode;
  value: number | string;
  label: string;
  variant?: 'default' | 'highlight';
};

/**
 * Propsy dla komponentu MenuTile
 */
export type MenuTileProps = {
  icon: React.ReactNode;
  title: string;
  description: string;
  href: string;
  variant?: 'default' | 'primary';
};

/**
 * Profil użytkownika dla wyświetlenia w UI
 */
export type UserProfile = {
  id: string;
  email: string;
  username?: string;
  avatar_url?: string;
};

/**
 * Odpowiedź z endpointu statystyk (jeśli zostanie stworzony)
 */
export type DashboardStatsResponse = {
  stats: DashboardStats;
};

// ============================================================================
// GENERATIONS VIEW MODELS (Frontend specific types)
// ============================================================================

/**
 * Props dla głównego widoku listy generacji
 */
export type GenerationsViewProps = {
  /** Początkowa strona z query params */
  initialPage?: number;
};

/**
 * Props dla komponentu GenerationList
 */
export type GenerationListProps = {
  /** Lista generacji do wyświetlenia */
  generations: GenerationDTO[];
  /** Callback wywoływany po kliknięciu wiersza */
  onRowClick: (id: number) => void;
};

/**
 * Props dla pojedynczego wiersza w tabeli generacji
 */
export type GenerationRowProps = {
  /** Dane pojedynczej generacji */
  generation: GenerationDTO;
  /** Callback wywoływany po kliknięciu wiersza */
  onRowClick: (id: number) => void;
};

/**
 * Props dla wskaźnika akceptacji fiszek
 */
export type AcceptanceRateIndicatorProps = {
  /** Liczba wygenerowanych fiszek */
  generatedCount: number;
  /** Liczba zaakceptowanych bez edycji (null jeśli brak) */
  acceptedUnedited: number | null;
  /** Liczba zaakceptowanych z edycją (null jeśli brak) */
  acceptedEdited: number | null;
};

/**
 * ViewModel dla wskaźnika akceptacji (wyliczone wartości)
 */
export type AcceptanceRateViewModel = {
  /** Procent akceptacji (0-100) */
  percentage: number;
  /** Liczba zaakceptowanych bez edycji */
  acceptedUnedited: number;
  /** Liczba zaakceptowanych z edycją */
  acceptedEdited: number;
  /** Całkowita liczba zaakceptowanych */
  totalAccepted: number;
  /** Wariant kolorystyczny dla UI */
  variant: 'low' | 'medium' | 'high'; // low: <50%, medium: 50-74%, high: >=75%
};

/**
 * Props dla widoku szczegółów generacji
 */
export type GenerationDetailViewProps = {
  /** ID generacji z URL params */
  generationId: number;
};

/**
 * Props dla nagłówka widoku szczegółów
 */
export type GenerationDetailHeaderProps = {
  /** Dane generacji */
  generation: GenerationDetailDTO;
};

/**
 * Props dla gridu statystyk generacji
 */
export type GenerationStatsGridProps = {
  /** Dane generacji */
  generation: GenerationDetailDTO;
};

/**
 * Props dla sekcji z tekstem źródłowym
 */
export type SourceTextSectionProps = {
  /** Hash tekstu źródłowego (SHA-256) */
  sourceTextHash: string;
  /** Długość tekstu źródłowego w znakach */
  sourceTextLength: number;
};

/**
 * Props dla sekcji z powiązanymi fiszkami
 */
export type AssociatedFlashcardsSectionProps = {
  /** Lista powiązanych fiszek */
  flashcards: Pick<FlashcardDTO, 'id' | 'front' | 'back' | 'source'>[];
};

// ============================================================================
// STUDY SESSION VIEW MODELS (Frontend specific types)
// ============================================================================

/**
 * Poziom jakości odpowiedzi w algorytmie SM-2
 * 0 = Again (całkowite zapomnienie)
 * 1 = Hard (z trudnością)
 * 2 = Good (poprawnie)
 * 3 = Easy (łatwo)
 */
export type SM2Quality = 0 | 1 | 2 | 3;

/**
 * Etykiety dla przycisków oceny
 */
export type RatingLabel = {
  quality: SM2Quality;
  label: string;
  description: string;
  color: 'red' | 'orange' | 'green' | 'blue';
  icon: string; // nazwa ikony z lucide-react
  keyboardShortcut: '1' | '2' | '3' | '4';
};

/**
 * Dane SM-2 przechowywane dla każdej fiszki w localStorage
 */
export type SM2ReviewData = {
  /** ID fiszki */
  flashcard_id: number;
  
  /** Współczynnik łatwości (E-Factor), zakres 1.3 - 2.5 */
  easiness: number;
  
  /** Interwał powtórek w dniach */
  interval: number;
  
  /** Liczba prawidłowych powtórzeń z rzędu */
  repetitions: number;
  
  /** Data następnej zaplanowanej powtórki (ISO string) */
  next_review: string;
  
  /** Data ostatniej powtórki (ISO string) */
  last_reviewed: string | null;
};

/**
 * Fiszka wraz z danymi SM-2 progress
 */
export type FlashcardWithProgress = {
  flashcard: FlashcardDTO;
  sm2Data: SM2ReviewData;
  isDue: boolean; // czy fiszka jest gotowa do powtórki
};

/**
 * Stan sesji nauki
 */
export type StudySessionState = 
  | { type: 'initializing' }
  | { type: 'empty' } // brak fiszek
  | { type: 'active'; currentCard: FlashcardWithProgress; isFlipped: boolean }
  | { type: 'completed'; stats: SessionStats };

/**
 * Statystyki sesji nauki
 */
export type SessionStats = {
  /** Całkowita liczba przejrzanych fiszek */
  totalReviewed: number;
  
  /** Czas trwania sesji w sekundach */
  durationSeconds: number;
  
  /** Breakdown ocen */
  ratings: {
    again: number; // quality 0
    hard: number;  // quality 1
    good: number;  // quality 2
    easy: number;  // quality 3
  };
  
  /** Data rozpoczęcia sesji (ISO string) */
  startedAt: string;
  
  /** Data zakończenia sesji (ISO string) */
  completedAt: string;
};

/**
 * Props dla głównego widoku sesji nauki
 */
export type StudySessionViewProps = {
  // Brak propsów - wszystkie dane ładowane dynamicznie
};

/**
 * Props dla header sesji nauki
 */
export type StudySessionHeaderProps = {
  currentIndex: number;
  totalCards: number;
  reviewedCount: number;
  remainingCount: number;
  onExit: () => void;
};

/**
 * Props dla progress bar
 */
export type StudyProgressBarProps = {
  current: number; // 1-based
  total: number;
};

/**
 * Props dla karty fiszki
 */
export type StudyCardProps = {
  flashcard: FlashcardDTO;
  isFlipped: boolean;
  onFlip?: () => void;
};

/**
 * Props dla przycisku flip
 */
export type FlipButtonProps = {
  onFlip: () => void;
};

/**
 * Props dla kontrolek oceny
 */
export type StudyControlsProps = {
  isFlipped: boolean;
  onRate: (quality: SM2Quality) => void;
  isProcessing: boolean;
};

/**
 * Props dla ekranu ukończenia
 */
export type CompletedStateProps = {
  stats: SessionStats;
  onRestart: () => void;
  onExit: () => void;
};

/**
 * Konfiguracja localStorage dla study session
 */
export type StudyProgressStorage = {
  /** Mapa flashcard_id → SM2ReviewData */
  reviews: Record<number, SM2ReviewData>;
  
  /** Timestamp ostatniej aktualizacji */
  lastUpdated: string;
  
  /** Wersja schema (dla migracji w przyszłości) */
  version: number;
};

/**
 * Parametry algorytmu SM-2
 */
export type SM2Params = {
  /** Minimalny E-Factor (default: 1.3) */
  minEasiness: number;
  
  /** Maksymalny E-Factor (default: 2.5) */
  maxEasiness: number;
  
  /** Początkowy E-Factor dla nowych fiszek (default: 2.5) */
  initialEasiness: number;
};

/**
 * Wynik kalkulacji SM-2
 */
export type SM2Result = {
  /** Nowy E-Factor */
  easiness: number;
  
  /** Nowy interwał w dniach */
  interval: number;
  
  /** Nowa liczba repetitions */
  repetitions: number;
  
  /** Data następnej powtórki (ISO string) */
  nextReview: string;
};

